export enum PROGRAM_FUNCTION {
  END = 'END',
}

export enum DATABASE_FUNCTION {
  SET = 'SET',
  GET = 'GET',
  UNSET = 'UNSET',
  NUMEQUALTO = 'NUMEQUALTO',
}

export enum TRANSACTION_FUNCTION {
  BEGIN = 'BEGIN',
  ROLLBACK = 'ROLLBACK',
  COMMIT = 'COMMIT',
}

export const REQUIRED_PARAMS = {
  [DATABASE_FUNCTION.SET]: 2,
  [DATABASE_FUNCTION.GET]: 1,
  [DATABASE_FUNCTION.UNSET]: 1,
  [DATABASE_FUNCTION.NUMEQUALTO]: 1,
};
